In [ ]:
ls

'My Drive'/


In [ ]:
from google.colab import drive
drive.mount("AIML")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at AIML


In [ ]:
%cd /content/AIML

/content/AIML


#Numpy programs

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.size

12

In [ ]:
 i = np.transpose(b) #Permute array dimensions
 i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
temp=np.array([1,2,3])
temp#if this is used before print statement the o/p is printed only once
print(temp)

[1 2 3]


In [ ]:
temp=np.array([1,2,3])
temp#if this is used before print statement the o/p is printed only once
print(temp)
temp#this gives output

[1 2 3]


array([1, 2, 3])

In [ ]:
tmp2=([[1,2],[3,4]])
tmp2

[[1, 2], [3, 4]]

In [ ]:
tmp3=np.array([[5,6,7],[7,8,9]])
tmp3

array([[5, 6, 7],
       [7, 8, 9]])

In [ ]:
tmp4=np.array([[6,7,8],[5,4,3],[9,0,8],[7,6,5]])
tmp4

array([[6, 7, 8],
       [5, 4, 3],
       [9, 0, 8],
       [7, 6, 5]])

#Sumofnumbers

In [ ]:
def getsum(x=10,y=9):
  return x+y
getsum(9,8)

17

In [ ]:
getsum()

19

In [ ]:
getsum(0)

9

In [ ]:
l3=[9,8,7]
l4=[8,7,6]
tmp4=np.array([[9,8,7],[8,7,6],l3,l4])
tmp4

array([[9, 8, 7],
       [8, 7, 6],
       [9, 8, 7],
       [8, 7, 6]])

In [ ]:
tmp4.shape

(4, 3)

In [ ]:
tmp4.size#this gives how many elements in array

12

In [ ]:
import numpy as np
l3=[9,8,7]
l4=[8,7,6]
tmp4=np.array([[9,8,7],[8,7,6],l3,l4])
tmp5=np.transpose(tmp4)
tmp5
temp6=tmp5
temp6[2][1]

6

In [ ]:
 import numpy as np
 np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
 import numpy as np
 d = np.arange(10,25,5)
 print(d)

[10 15 20]


In [ ]:
import numpy as np
np.random.random((2,2))

array([[0.79678289, 0.77433507],
       [0.20047179, 0.53977021]])

In [ ]:
tmp4.sort() #Sort an array
tmp4.sort(axis=0)
tmp4

array([[6, 7, 8],
       [6, 7, 8],
       [7, 8, 9],
       [7, 8, 9]])

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)

#Comparision

In [ ]:
a==b

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a<2

array([ True, False, False])

In [ ]:
np.array_equal(a, b)

False

#Aggregate functions

In [ ]:
a.sum()

6

In [ ]:
b.sum()

21.5

In [ ]:
a.min()

1

In [ ]:
b.max(axis=0)

array([4., 5., 6.])

In [ ]:
a.mean()

2.0

In [ ]:
h = a.view() #Create a view of the array with the same data
np.copy(a) #Create a copy of the array
h = a.copy()

In [ ]:
h

array([1, 2, 3])

#subsetting and slicing

In [ ]:
a[2]

3

In [ ]:
b[1,2]

6.0

In [ ]:
c[1,...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [ ]:
a[ : :-1] #Reversed array a array([3, 2, 1])

array([3, 2, 1])

In [ ]:
a[a<2]

array([1])

In [ ]:
#Changing Array Shape
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
#Fancy Indexing
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [ ]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows


array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

#Concatenating

In [ ]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [ ]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

#Splitting

In [ ]:
np.hsplit(a,3)


[array([1]), array([2]), array([3])]

In [ ]:
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]

#Arithmetic Operations

In [ ]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
f=b+a
f

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])